### ISSUE TITLE
Editors cannot correctly embed media items using an embed code

### ISSUE THREAD

**Issue by krista-ramakers** [driebit/ginger#176] opened 2016-09-08 12:22 UTC
Came across this because an editor would like to embed a Soundcloud player in the body text of an article on their website. 

If the editor chooses:
- either the 'insert a Zotonic media item' button, or the 'add media item' button below the text editor
- selects the 'embedcode' tab
- provides the necessary information + embed code
- clicks 'create media item'

An 'empty' media item is created (see added screenshots). The editor then has to visit the full edit page of the media item and add media file/content again by choosing 'embed code' in order for the embed item to work as it should. Or they can create a new media item from scratch and add it to their article by using 'find an existing page'. 

![bewerken_ de_mix _ _maand_van_de_geschiedenis_admin_](https://cloud.githubusercontent.com/assets/20204550/18349063/73dd004a-75cf-11e6-8588-1be657b78874.png)

**Comment by ddeboer** [comment] 2016-09-09 13:24
@Dirklectisch Do you have some time to reproduce this and check the logs?

**Comment by DorienD** [comment] 2016-09-09 13:24
I can do that!

**Comment by ddeboer** [comment] 2016-09-09 13:25
@krista-ramakers Do you also find this bug on production (Zotonic 0.19)?

**Comment by DorienD** [comment] 2016-09-09 13:27
On my development enviroment i get this error: 

`13:27:03.894 [error] webmachine_mochiweb:119 stop_request 500 (reason {{badmatch,{error,enoent}},[{controller_admin_media_preview,to_image,2,[{file,"modules/mod_admin/controllers/controller_admin_media_preview.erl"},{line,68}]},{webmachine_controller,controller_call,3,[{file,"src/webmachine_controller.erl"},{line,206}]},{webmachine_decision_core,decision,3,[{file,"src/webmachine_decision_core.erl"},{line,578}]},{webmachine_decision_core,handle_request,2,[{file,"src/webmachine_decision_core.erl"},{line,31}]},{webmachine_mochiweb,loop,2,[{file,"src/webmachine_mochiweb.erl"},{line,100}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,104}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]})
zotonic_1   | 13:27:03.902 [error] Error in process <0.6321.10> on node zotonic001@6043613de93a with exit value:
zotonic_1   | {{badmatch,{ok,0}},[{m_media,save_preview,4,[{file,"src/models/m_media.erl"},{line,825}]}]}`

**Comment by DorienD** [comment] 2016-09-09 13:31
This is also broken on production (tried it on nieuwwestexpress)

**Comment by DorienD** [comment] 2016-09-09 13:32
I forgot a part of the initial error message: 

`13:27:05.273 [warning] webmachine_mochiweb:221 caught error {stop_request,500,{function_clause,[{filter_stringify,stringify_1,[{{badmatch,{error,enoent}},[{controller_admin_media_preview,to_image,2,[{file,"modules/mod_admin/controllers/controller_admin_media_preview.erl"},{line,68}]},{webmachine_controller,controller_call,3,[{file,"src/webmachine_controller.erl"},{line,206}]},{webmachine_decision_core,decision,3,[{file,"src/webmachine_decision_core.erl"},{line,578}]},{webmachine_decision_core,handle_request,2,[{file,"src/webmachine_decision_core.erl"},{line,31}]},{webmachine_mochiweb,loop,2,[{file,"src/webmachine_mochiweb.erl"},{line,100}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,104}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{context,geheugenvanoost,{wm_reqdata,#Port<0.1072970>,{dict,7,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[[controller_module_error|controller_admin_media_preview]],[[ua_class|desktop],[ua_props,{is_user_select,true},{has_pointer,true},{is_desktop,true},{is_crawler,false},{is_wireless_device,false},{is_tablet,false},{ajax_support_javascript,true},{device_os,<<"-">>},{displayWidth,1920},{displayHeight,1200},{inputDevices,<<"-">>},{parentId,<<"generic-">>},{model,<<"browser">>},{vendor,<<"desktop">>},{id,<<"desktopDevice">>}]],[[zotonic_host|geheugenvanoost]],[[controller_module|controller_http_error],[http_status_code|500]],[],[],[],[],[],[],[],[],[[error_reason|{{badmatch,{error,enoent}},[{controller_admin_media_preview,to_image,2,[{file,"modules/mod_admin/controllers/controller_admin_media_preview.erl"},{line,68}]},{webmachine_controller,controller_call,3,[{file,"src/webmachine_controller.erl"},{line,206}]},{webmachine_decision_core,decision,3,[{file,"src/webmachine_decision_core.erl"},{line,578}]},{webmachine_decision_core,handle_request,2,[{file,"src/webmachine_decision_core.erl"},{line,31}]},{webmachine_mochiweb,loop,2,[{file,"src/webmachine_mochiweb.erl"},{line,100}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},...]},...]}]],...}}},...},...}],...},...]}} (stacktrace [{webmachine_decision_core,handle_request,2,[{file,"src/webmachine_decision_core.erl"},{line,37}]},{webmachine_mochiweb,render_error,4,[{file,"src/webmachine_mochiweb.erl"},{line,211}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,104}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}])`

**Comment by ddeboer** [comment] 2016-09-09 13:33
Thanks, @DorienD.

So not a new bug and therefore shouldn’t delay deploying the new Ginger/Zotonic versions. This does need to fixed, though. @Dirklectisch? :wink:

**Comment by Dirklectisch** [comment] 2016-09-09 14:47
A badmatch in stringify usually means we are trying to print something that we shouldn't.

**Comment by ddeboer** [comment] 2016-09-29 08:38
Embedding seems to work fine now on acc and prod.

@krista-ramakers Do you still see the problem?

**Comment by krista-ramakers** [comment] 2016-09-29 13:05
Yep, I still do on both acc. and prod., when I'm logged in as editor and I create a new page and try to embed a YouTube video/Soundcloud player using the embedcode, Ginger creates an 'empty' media item.

**Comment by DorienD** [comment] 2016-10-13 15:00
Ping! @ddeboer @Dirklectisch  this is also an error for the ginger embed, admins can embed pages but other user groups can't....

This is the error.

`15:00:03.105 [error] webmachine_mochiweb:119 stop_request 500 (reason {{badmatch,{error,enoent}},[{controller_admin_media_preview,to_image,2,[{file,"modules/mod_admin/controllers/controller_admin_media_preview.erl"},{line,68}]},{webmachine_controller,controller_call,3,[{file,"src/webmachine_controller.erl"},{line,206}]},{webmachine_decision_core,decision,3,[{file,"src/webmachine_decision_core.erl"},{line,578}]},{webmachine_decision_core,handle_request,2,[{file,"src/webmachine_decision_core.erl"},{line,31}]},{webmachine_mochiweb,loop,2,[{file,"src/webmachine_mochiweb.erl"},{line,100}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,104}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]})
zotonic_1   | 15:00:03.940 [warning] webmachine_mochiweb:221 caught error {stop_request,500,{function_clause,[{filter_stringify,stringify_1,[{{badmatch,{error,enoent}},[{controller_admin_media_preview,to_image,2,[{file,"modules/mod_admin/controllers/controller_admin_media_preview.erl"},{line,68}]},{webmachine_controller,controller_call,3,[{file,"src/webmachine_controller.erl"},{line,206}]},{webmachine_decision_core,decision,3,[{file,"src/webmachine_decision_core.erl"},{line,578}]},{webmachine_decision_core,handle_request,2,[{file,"src/webmachine_decision_core.erl"},{line,31}]},{webmachine_mochiweb,loop,2,[{file,"src/webmachine_mochiweb.erl"},{line,100}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,104}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{context,hart_amsterdammuseum,{wm_reqdata,#Port<0.143002>,{dict,7,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[[controller_module_error|controller_admin_media_preview]],[[ua_class|desktop],[ua_props,{is_user_select,true},{has_pointer,true},{is_desktop,true},{is_crawler,false},{is_wireless_device,false},{is_tablet,false},{ajax_support_javascript,true},{device_os,<<"-">>},{displayWidth,1920},{displayHeight,1200},{inputDevices,<<"-">>},{parentId,<<"generic-">>},{model,<<"browser">>},{vendor,<<"desktop">>},{id,<<"desktopDevice">>}]],[[zotonic_host|hart_amsterdammuseum]],[[controller_module|controller_http_error],[http_status_code|500]],[],[],[],[],[],[],[],[],[[error_reason|{{badmatch,{error,enoent}},[{controller_admin_media_preview,to_image,2,[{file,"modules/mod_admin/controllers/controller_admin_media_preview.erl"},{line,68}]},{webmachine_controller,controller_call,3,[{file,"src/webmachine_controller.erl"},{line,206}]},{webmachine_decision_core,decision,3,[{file,"src/webmachine_decision_core.erl"},{line,578}]},{webmachine_decision_core,handle_request,2,[{file,"src/webmachine_decision_core.erl"},{line,31}]},{webmachine_mochiweb,loop,2,[{file,"src/webmachine_mochiweb.erl"},{line,100}]},{mochiweb_http,headers,5,[{file,"src/mochiweb..."},...]},...]}]],...}}},...},...}],...},...]}} (stacktrace [{webmachine_decision_core,handle_request,2,[{file,"src/webmachine_decision_core.erl"},{line,37}]},{webmachine_mochiweb,render_error,4,[{file,"src/webmachine_mochiweb.erl"},{line,211}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,104}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}])`

**Comment by ddeboer** [comment] 2016-10-13 15:34
I’ll have to look into this a little more: it seems embedding for the built-in types (such as YouTube) no longer works properly either, even if done by admins.

**Comment by DorienD** [comment] 2016-10-20 07:46
Can we give this a little priority? So it can be fixed faster? Since the ginger embed will be available with ginger 0.16 but nobody can use it because they can't embed.

**Comment by mworrell** [comment] 2016-11-29 15:05
Fixed in #1545 (part of Zotonic 0.23)

**Comment by ddeboer** [comment] 2016-11-29 15:06
Thanks Marc! 👏

**Closed by ddeboer** 2016-11-29 15:06 UTC
Labels: bug
