### ISSUE TITLE
Create direct download link for (PDF) files in body text

### ISSUE THREAD

**Issue by krista-ramakers** [driebit/ginger#213] opened 2016-11-04 13:41 UTC
Currently, it is only possible to have a hyperlink to a PDF file under media items. 
It would be nice to enable the user to create a hyperlink to (download) a PDF file in the body text, using the text editor (you can create a hyperlink to an internal page now in the body text, but if you click it, it takes you to a document page that has to be styled etc. and on this page you have to click again to download the file). 

We would imagine it to look something similar to the 'create external hyperlink' dialog, where you now select 'target: none/new window' and then for a PDF file this might be 'target: new tab/direct download'.

**Comment by ddeboer** [comment] 2016-11-04 15:51
Duplicate of #160.

**Closed by ddeboer** 2016-11-04 15:51 UTC
